### ISSUE TITLE
Categories corresp to LOC should have gloss[@type='loc']

### ISSUE THREAD

**Issue by telic** [internetshakespeare/ise3#1]
Add a Schematron rule that all responsibility categories defined in our taxonomy which have a corresponding MARC relator also have a "loc" gloss type.

Something like:
```
<rule context="id('iseRespTaxonomy')/category[starts-with(@corresp, 'loc:')]">
  <assert test="exists(catDesc/gloss[@type='loc'])"/>
</rule>
```

**Comment by joeytakeda** [comment]
Resolved in SVN -r 248.
